steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/testcicd0811/loan-calculator', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/testcicd0811/loan-calculator']

options:
  logging: 'CLOUD_LOGGING_ONLY'  # This setting is optional, adjust as needed

images:
  - 'gcr.io/testcicd0811/loan-calculator'
