steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/testcicd0811/loan-calculator', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/testcicd0811/loan-calculator']

images:
  - 'gcr.io/testcicd0811/loan-calculator'
